# Generated by Django 2.2.1 on 2019-07-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double')], max_length=20)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adult', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('children', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
            ],
        ),
    ]
