# Generated by Django 2.2.1 on 2019-07-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='adult',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='children',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0),
        ),
    ]
