# Generated by Django 2.2.1 on 2019-07-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190720_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='adult',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('Executive', 'Executive Room'), ('Mini', 'Mini Suite'), ('presidential', 'Presidential Suite'), ('Deluxe', 'Deluxe Suite'), ('Twin', 'Twin Apartment')], default='Single Room', max_length=20),
        ),
    ]
